### ISSUE TITLE
COVIN DATA FETCH PROBLEM + DROPDOWN F.RQST

### ISSUE THREAD

**Issue by Anubhav-developr** [Anubhav-developr/cofwah#1]
1)   in this database u will get a file named Vaccine.js that's our functional component .... in this component i had fetched dynamic data entered by user and appended it to url of fetch but problem is coming that can't map undefined .....
![image](https://user-images.githubusercontent.com/71844334/120885390-3e2a6000-c606-11eb-89f7-b4ed31485932.png)

2) we want 2 dynamic dropdown menus using material ui / normal js whose each option will be the name of state and name of city.. using json object using .(dot) operator thats needed... extra u can add with ur creativity 

both works needed to be done in Vaccine.js component

**Comment by imrachu** [comment]
# Map method only works on arrays.
Map method only works on arrays, the data stored in data variable is of object type. You can not map through the values of data.

**Comment by Anubhav-developr** [comment]
Ok ok thanks .. i'll see this later im busy right now
